# PyTorch Fundamentals

## Importing PyTorch

In [1]:
import torch
torch.__version__

'2.8.0+cpu'

## Introduction to Tensors
### Scalar

In [ ]:
# Scalar
scalar = torch.tensor(7)
scalar

tensor([7])

In [12]:
#Prints out Dimension of a Tensor
scalar.ndim

1

In [8]:
# Get the Python number within a tensor (only works with one-element tensors)
scalar.item()

7

### Vectors

In [9]:
# Vector 
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [ ]:
# Vector Dimension:
# Tensor dimensions = number of outer [ ] layers.

vector.ndim

1

In [13]:
#Check the Shape of Vector
vector.shape

torch.Size([2])

### Matrix

In [14]:
#Matrix 
MATRIX = torch.tensor([[7,8],
                      [9,10]])

MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
print(MATRIX.ndim) #2 Dimensions, 2 Square Brackets
print(MATRIX.shape) #[2,2], two elements deep, two elements wide

2
torch.Size([2, 2])


### Tensor

In [19]:
#Tensor 
TENSOR = torch.tensor([[[1,2,3],
                      [3,6,9],
                      [2,4,5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [ ]:
print(TENSOR.ndim)
print(TENSOR.shape) 

#Output is [1,3,3] meaning there's one dimension of a 3,3


3
torch.Size([1, 3, 3])


In [28]:
TENSORTEST1 = torch.tensor([[7,4],
                            [0,1],
                            [1,9],
                            [2,3],
                            [5,6],
                            [8,8]])

print(TENSORTEST1.ndim)
print(TENSORTEST1.shape)

2
torch.Size([6, 2])


### Random Tensors

In [29]:
# Create a random tensor of size (3,4)
random_tensor = torch.rand(size=(3,4))
random_tensor, random_tensor.dtype

(tensor([[0.4058, 0.0056, 0.5172, 0.5546],
         [0.4737, 0.2224, 0.1281, 0.1490],
         [0.5349, 0.6570, 0.0701, 0.7573]]),
 torch.float32)

Random Tensors can have different sizes, whichever we want, example:
Height = 224
Width = 224
Color Channels = 3
([height], [width], color_channels)

In [32]:

#Create a random tensor of size (224,224,3)
random_image_size_tensor = torch.rand(size=(224,224,3))
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

### Zeroes and Ones

Creating Tensor of Zeroes and Ones, e.g. All Zeroes

In [33]:
# Create a tensor of all zeroes
zeros = torch.zeros(size=(3,4))
zeros, zeros.dtype


(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 torch.float32)

In [34]:
#Create a tensor of all ones
ones = torch.ones(size=(3,4))
ones, ones.dtype

(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 torch.float32)

### Creating a range and tensors like

You can use ```torch.arange(start, end, step)``` to createa  tensor based on preferred range.
Where:
- `start`= start of range
- `end` = end of range
- `step` = how many steps between each value, e.g. 1

In [44]:
#Create range of values of 0 to 10
zero_to_ten = torch.arange(start=0, end=10, step=1)
zero_to_ten

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [48]:
#Creating tensor similar shape to previous tensors using torch.zeroes_like
ten_zeros = torch.zeros_like(input=zero_to_ten) #will have same shape, but all zeros
print(ten_zeros)

ten_ones = torch.ones_like(input=zero_to_ten) #will have same shape, but all ones
print(ten_ones)

ten_randoms = torch.rand_like(zero_to_ten, dtype=torch.float)
print(ten_randoms)

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])
tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])
tensor([0.7354, 0.6396, 0.8078, 0.1304, 0.0794, 0.9466, 0.1401, 0.0845, 0.2206,
        0.9816])


### Tensor Datatypes

In [51]:
#Default datatype for tensors is float32

float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, #defaults to None, which is torch.float32 or whatever datatype is passed
                               device=None, #defaults to None, which uses default tensor type
                               requires_grad=False #if true, operations performed are recorded
                               )
float_32_tensor.dtype, float_32_tensor.device

(torch.float32, device(type='cpu'))

In [52]:
#Creating dtype float16
float_16_tensor = torch.tensor([3.0, 5.0, 9.0],
                               dtype=torch.float16)
float_16_tensor.dtype

torch.float16

## Getting information from Tensors
Common attributes to check:

- **`.shape`** → tensor dimensions (rows, cols, etc.)  
- **`.dtype`** → data type of elements (float, int, etc.)  
- **`.device`** → where it’s stored (CPU or GPU)  

In [54]:
#Create a random tensor
some_tensor = torch.rand(3,4)

#Find out details about it
print(some_tensor)
print()
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Device tensor is stored on: {some_tensor.device}")

tensor([[0.1721, 0.3632, 0.8006, 0.8269],
        [0.7201, 0.7688, 0.1841, 0.6352],
        [0.6205, 0.9683, 0.7540, 0.5206]])

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


## Manipulating Tensors (tensor operations)

Deep learning uses **tensors** to represent data and applies basic operations to learn patterns:

- Addition
- Subtraction
- Element-wise multiplication
- Division
- Matrix multiplication

These form the core building blocks of neural networks.



### Basic Operations


In [ ]:
#ADDITION
#Create a tensor of values and add a number to it
tensor = torch.tensor([1,2,3])
tensor + 10


tensor([11, 12, 13])

In [56]:
#MULTIPLICATION
# Multiply it by 10
tensor * 10

tensor([10, 20, 30])

Tensor values doesn't change, until they are reassigned

In [57]:
tensor

tensor([1, 2, 3])

In [58]:
#Subtraction, and reassign

tensor = tensor - 10
tensor

tensor([-9, -8, -7])

In [63]:
#Will be changed after
#add and reassign
tensor = tensor + 10
tensor

tensor([1, 2, 3])

In [ ]:
#Torch Multiplication, will still be unchanged, using torch.multiply
torch.multiply(tensor, 10)

#However, it's still more common to use *, than methods

tensor([10, 20, 30])

### Matrix Multiplication 

Matrix multiplication is a key operation in deep learning, implemented in PyTorch via `torch.matmul()`.

**Rules:**
1. **Inner dimensions must match**  
   - `(3, 2) @ (3, 2)` → ❌  
   - `(2, 3) @ (3, 2)` → ✅  
   - `(3, 2) @ (2, 3)` → ✅  

2. **Result shape = outer dimensions**  
   - `(2, 3) @ (3, 2)` → `(2, 2)`  
   - `(3, 2) @ (2, 3)` → `(3, 3)`  

**Note:** `@` in Python denotes matrix multiplication.


In [ ]:
#Create a tensor and perform element-wise multiplication and matrix multiplication
import torch
tensor = torch.tensor([1,2,3])

tensor.shape


#### Element-wise vs Matrix Multiplication — Summary

For a tensor `[1, 2, 3]`:

- **Element-wise multiplication**: Multiply corresponding elements.  
  `[1*1, 2*2, 3*3]` → `[1, 4, 9]`  
  **Code:** `tensor * tensor`

- **Matrix multiplication**: Multiply and sum products.  
  `[1*1 + 2*2 + 3*3]` → `[14]`  
  **Code:** `tensor.matmul(tensor)`

**Key difference**: Matrix multiplication adds the products; element-wise does not.


In [68]:
#Element-wise matrix multiplication
print(f"Element-Wise Matrix Multiplication: {tensor * tensor}")

#Matrix multiplication
print(f"Matrix Multiplication: {torch.matmul(tensor, tensor)}")


Element-Wise Matrix Multiplication: tensor([1, 4, 9])
Matrix Multiplication: 14


Doing matrix multiplication is doable but not recommended as `torch.matmul()` method is faster

In [70]:
%%time 
# Matrix Multiplication by Hand
# (Avoid doing operations with for loops, because they're expensive)

value = 0 
for i in range(len(tensor)):
    value += tensor[i] * tensor[i]

value


CPU times: total: 0 ns
Wall time: 135 μs


tensor(14)

In [71]:
%%time 
torch.matmul(tensor, tensor)


CPU times: total: 0 ns
Wall time: 45.8 μs


tensor(14)